### PR TITLE
zh_cn translation

### PR DESCRIPTION
**Pull request by HaHaWTH**

### CODE REVIEW

**Comment by TheHamester** [comment]
Provided localization is very appreciated, but since tooltips (hover over text) were hardcoded in english in the config class itself from mere neglegence of the fact somebody would pull request a localization, I made a commit that exposes tooltip lagnauge keys into the lang file as well. If that's not too big of an ask, I'd like to ask to translate the tooltips too. Thank you very much for your contribution!

**Comment by TheHamester** [comment]
please confirm if youre planning on translating tooltips/hover over text. in case the answer is no, hover over text will remain english in the localization. fetch the changes to see the tooltip langauge keys

**Comment by TheHamester** [comment]
the translation keys for enabling hit indication are
`hitindication.gui.config.indicators.enable_hit_indication=Enable Hit Indication`
and
`hitindication.gui.config.indicators.enable_hit_indication.tooltip=Enables hit indication.`

reference to https://github.com/TheHamester/HitIndicator/issues/5

**Comment by HaHaWTH** [comment]
OK, this language file is for the 1.12.2branch and I'll upload other files later:)

**Comment by TheHamester** [comment]
theres still no all of the tooltips look at my latest commit to 1.12.2

**Comment by TheHamester** [comment]
also, i dont think for further versions its possible to translate config files, even tho in the config spec builder there is .translate method, it doesnt seem to do anything, correct me if im wrong

**Comment by TheHamester** [comment]
https://github.com/TheHamester/HitIndicator/blob/1.12.2/src/main/resources/assets/hitindication/lang/en_us.lang

> theres still no all of the tooltips look at my latest commit to 1.12.2

**Comment by HaHaWTH** [comment]
> https://github.com/TheHamester/HitIndicator/blob/1.12.2/src/main/resources/assets/hitindication/lang/en_us.lang
> 
> > theres still no all of the tooltips look at my latest commit to 1.12.2

Finished!

**Comment by TheHamester** [comment]
ye that looks good, thank you!!

**Comment by TheHamester** [comment]
saying in advance, i dont think zh_cn localization goes into other versions. forge doesnt seem to support translating config files in 1.16.5 and 1.18.2, sorry.

**Comment by HaHaWTH** [comment]
> saying in advance, i dont think zh_cn localization goes into other versions. forge doesnt seem to support translating config files in 1.16.5 and 1.18.2, sorry.

Ahh....Maybe you need to convert .lang file into .json file, Forge in newer Minecraft versions only support json as localization files:(

**Comment by HaHaWTH** [comment]
I put my localization file into the jar file of this mod and it works perfectly :)

**Comment by TheHamester** [comment]
i did use json files. thing is you see, in further versions an external mod is required to generate config screens. 
and while i did find actual localization for froge configs in files, even they work really inconsistantly. i did try the same way they implemented it for my own config, it doesnt seem to work, thich is reaaaaally weird
image

**Comment by TheHamester** [comment]
but 1.12 works perfectly ye

**Comment by TheHamester** [comment]
oh, ok, got it to work in 1.18.2, they just dont support tooltips

**Comment by TheHamester** [comment]
ill make json files myself

**Comment by HaHaWTH** [comment]
> i did use json files. thing is you see, in further versions an external mod is required to generate config screens.
> and while i did find actual localization for froge configs in files, even they work really inconsistantly. i did try the same way they implemented it for my own config, it doesnt seem to work, thich is reaaaaally weird
> image

emmm...Maybe you need to switch game language to Simplified Chinese instead of Traditional Chinese?

**Comment by HaHaWTH** [comment]
Wait.....Newer versions of Forge does not support tooltips?! I know little about modern Minecraft versions🧐

**Comment by TheHamester** [comment]
translated tooltips for configs, ye

**Pull request merged**
